# Bullet Digital Media monorepo - convenience targets
# Single entrypoint covering both pnpm (TS) and uv (Python) stacks.

.PHONY: install lint typecheck build test precommit-install precommit-run \
        api-test api-dev dashboard-build clean help codegen e2e \
        review-gate review-gate-db \
        db-upgrade db-downgrade db-revision db-reset db-seed-team

help:
	@echo "Available targets:"
	@echo "  install            Install JS (pnpm) and Python (uv) deps"
	@echo "  precommit-install  Install the local git pre-commit hook"
	@echo "  precommit-run      Run all pre-commit hooks against all files"
	@echo "  lint               Run linters across both stacks"
	@echo "  typecheck          Run TS typecheck across all workspace packages"
	@echo "  build              Build all workspace packages"
	@echo "  codegen            Regenerate the OpenAPI doc + typed TS client (S1-17)"
	@echo "  test               Run JS + Python test suites"
	@echo "  review-gate        Run the reviewer's own catch techniques against the diff"
	@echo "  review-gate-db     Mutation-test the db-marked guards too (needs Postgres up)"
	@echo "  e2e                Run the Playwright E2E suite (needs Postgres up + db-upgrade + DATABASE_URL)"
	@echo "  api-dev            Run the FastAPI app locally on :8000 with reload"
	@echo "  db-upgrade         Run Alembic upgrade head against DATABASE_URL"
	@echo "  db-downgrade       Run Alembic downgrade -1"
	@echo "  db-revision m=...  Create a new autogenerated migration"
	@echo "  db-reset           Downgrade to base then upgrade to head"
	@echo "  db-seed-team       Idempotently seed the four named team users (S1-11)"
	@echo "  clean              Remove build artefacts and caches"

install:
	pnpm install
	uv sync --all-packages

precommit-install:
	uvx pre-commit install

precommit-run:
	uvx pre-commit run --all-files

lint:
	pnpm -r --if-present lint
	uv run ruff check apps/api

# Mechanized review techniques (S1-26b/c round 5). Run BEFORE raising a PR:
# it catches the revert-green / silently-passing / net-new-PII classes that
# produced findings in five consecutive review rounds. BASE overrides the
# branch to diff against.
# Runs BOTH halves, and the mutation half includes the db-marked guards by
# default. Needs Postgres up: without it those tests SKIP, a skipped test cannot
# fail, so it cannot prove a guard - the runner reports UNPROVEN and FAILS.
# Pass MUTATE_ARGS=--allow-unproven on a laptop with no Postgres, knowing those
# guards are then unverified.
#
# The static half runs under `-` so a finding there does not hide the mutation
# results, which are the higher-value half; the explicit exit re-raises it.
review-gate:
	@uv run python apps/api/scripts/review_gate.py --base $(or $(BASE),main); static=$$?; \
	uv run python apps/api/scripts/review_gate_mutate.py --include-db $(MUTATE_ARGS); mutate=$$?; \
	if [ $$static -ne 0 ] || [ $$mutate -ne 0 ]; then exit 1; fi
# ^ NOT `exit $$((static + mutate))` (round 12, P3): shell exit codes are
# taken modulo 256, so two failures summing to 256 exited 0 - a green gate
# made of two red halves.

# The mutation half alone.
review-gate-db:
	uv run python apps/api/scripts/review_gate_mutate.py --include-db $(MUTATE_ARGS)

typecheck:
	pnpm -r --if-present typecheck

build:
	pnpm -r --if-present build

# Regenerate the OpenAPI document and the typed TS client (S1-17).
# Step 1 dumps apps/api's OpenAPI schema to packages/shared/openapi.json;
# step 2 generates the TS types from it. app.openapi() is pure schema
# generation - no server is started and no DB connection is opened, so the
# DATABASE_URL below only satisfies the required Settings field (never used
# to connect) and INNGEST_DEV=1 lets the app import without a signing key.
# CI runs this and fails on any git diff (drift between the committed client
# and the live API contract).
codegen:
	cd apps/api && DATABASE_URL=postgresql://codegen:codegen@localhost:5432/codegen INNGEST_DEV=1 uv run python scripts/dump_openapi.py
	pnpm --filter @bullet/shared codegen

test: api-test
	pnpm -r --if-present test

api-test:
	uv run pytest apps/api -q

# Playwright E2E suite (S1-18). Assumes the docker Postgres is up, migrations
# have been applied (make db-upgrade), and DATABASE_URL is exported. Playwright
# boots both the API (:8000) and the dashboard (:3000) itself and seeds the two
# fixture users via globalSetup before running the auth specs.
e2e:
	pnpm --filter @bullet/dashboard test:e2e

# Mirrors the Render staging start command. Render runs without --reload.
api-dev:
	cd apps/api && uv run uvicorn bullet_api.main:app --reload --host 0.0.0.0 --port 8000

# Database migrations (Alembic). Uses DATABASE_URL from the environment;
# defaults to the docker-compose Postgres via .env.
db-upgrade:
	cd apps/api && uv run alembic upgrade head

db-downgrade:
	cd apps/api && uv run alembic downgrade -1

# Usage: make db-revision m="add clients table"
db-revision:
	cd apps/api && uv run alembic revision --autogenerate -m "$(m)"

db-reset:
	cd apps/api && uv run alembic downgrade base && uv run alembic upgrade head

# Idempotent: re-running prints "already seeded" for existing rows. New
# rows include argon2id temp passwords printed to stdout for handoff.
db-seed-team:
	cd apps/api && uv run python -m bullet_api.scripts.seed_team

clean:
	find . -type d -name "node_modules" -prune -exec rm -rf {} +
	find . -type d -name ".next" -prune -exec rm -rf {} +
	find . -type d -name "dist" -prune -exec rm -rf {} +
	find . -type d -name "__pycache__" -prune -exec rm -rf {} +
	find . -type d -name ".pytest_cache" -prune -exec rm -rf {} +
	find . -type d -name ".ruff_cache" -prune -exec rm -rf {} +
