# Bullet Digital Media monorepo - convenience targets
# Single entrypoint covering both pnpm (TS) and uv (Python) stacks.

.PHONY: install lint typecheck build test precommit-install precommit-run \
        api-test dashboard-build clean help \
        db-upgrade db-downgrade db-revision db-reset

help:
	@echo "Available targets:"
	@echo "  install            Install JS (pnpm) and Python (uv) deps"
	@echo "  precommit-install  Install the local git pre-commit hook"
	@echo "  precommit-run      Run all pre-commit hooks against all files"
	@echo "  lint               Run linters across both stacks"
	@echo "  typecheck          Run TS typecheck across all workspace packages"
	@echo "  build              Build all workspace packages"
	@echo "  test               Run JS + Python test suites"
	@echo "  db-upgrade         Run Alembic upgrade head against DATABASE_URL"
	@echo "  db-downgrade       Run Alembic downgrade -1"
	@echo "  db-revision m=...  Create a new autogenerated migration"
	@echo "  db-reset           Downgrade to base then upgrade to head"
	@echo "  clean              Remove build artefacts and caches"

install:
	pnpm install
	uv sync --all-packages

precommit-install:
	uvx pre-commit install

precommit-run:
	uvx pre-commit run --all-files

lint:
	pnpm -r --if-present lint
	uv run ruff check apps/api

typecheck:
	pnpm -r --if-present typecheck

build:
	pnpm -r --if-present build

test: api-test
	pnpm -r --if-present test

api-test:
	uv run pytest apps/api -q

# Database migrations (Alembic). Uses DATABASE_URL from the environment;
# defaults to the docker-compose Postgres via .env.
db-upgrade:
	cd apps/api && uv run alembic upgrade head

db-downgrade:
	cd apps/api && uv run alembic downgrade -1

# Usage: make db-revision m="add clients table"
db-revision:
	cd apps/api && uv run alembic revision --autogenerate -m "$(m)"

db-reset:
	cd apps/api && uv run alembic downgrade base && uv run alembic upgrade head

clean:
	find . -type d -name "node_modules" -prune -exec rm -rf {} +
	find . -type d -name ".next" -prune -exec rm -rf {} +
	find . -type d -name "dist" -prune -exec rm -rf {} +
	find . -type d -name "__pycache__" -prune -exec rm -rf {} +
	find . -type d -name ".pytest_cache" -prune -exec rm -rf {} +
	find . -type d -name ".ruff_cache" -prune -exec rm -rf {} +
